### ISSUE TITLE
why is there a data_timeline.txt in msk_solid_heme

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/cmo-pipelines#1075]
We should not be pulling timeline information for the general cohort.  Why is there a treatment file in the folder?

https://github.mskcc.org/knowledgesystems/dmp-2023/blob/master/msk_solid_heme/data_timeline.txt

- [x] Remove Timeline for General Cohort
- [x] Check it won't be regenerated

**Comment by averyniceday** [comment]
MSKIMAPCT -- timeline for pediatric patients (can remove) + supplementary timeline dat for mskimpact (prepopulated redcap projects)

**Comment by averyniceday** [comment]
MSKIMAPCT -- timeline for pediatric patients (can remove) + supplementary timeline dat for mskimpact (prepopulated redcap projects)
