### ISSUE TITLE
Deploy Airflow to Dev 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/cmo-pipelines#1118]
Done Condition: Airflow is setup in dev cluster and available for testing - configurations and documentation checked in

**Comment by jamesqo** [comment]
Summary of blockers:

- [ ] Deploying Helm chart
  - [ ] EFS installation
    - [ ] Update trust policy to enable EFS installation
    - [ ] Install EFS plugin for EKS
    - [ ] Create EFS filesystem
  - [ ] gitSync
    - [ ] Enable cloning of Git repos on dev cluster using SSH url (`git@`)
      - [ ] Enable incoming SSH connections from `github.com`and `github.mskcc.org`
  - [ ] Datadog
    - [ ] Enable health checks for Airflow dev server
      - [ ] Use a valid SSL certificate for server
    - [ ] Enable metric collection for Airflow dev server
      - [ ] Use a valid SSL certificate for server
      - [ ] Install StatsD Airflow plugin
