### ISSUE TITLE
Setup S3 Pull/Push in CDM DAGs

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/cmo-pipelines#1144]
Changes to Chris' DAG running on TLL6 - setup authentication and push/pull in needed areas for 
- getting sample list
- delivering a combined cohort (solid_heme)

May involve installing AWS  cli

**Comment by callachennault** [comment]
cmo-pipelines PR: https://github.com/knowledgesystems/cmo-pipelines/pull/1130
dags PR: https://github.com/clinical-data-mining/dags/pull/8
cdm-cbioportal-etl PR: https://github.com/clinical-data-mining/cdm-cbioportal-etl/pull/57
