### ISSUE TITLE
Incorrect Part-C consent status

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/cmo-pipelines#693]
The following patients show Part C is NO when they have consented:

P-0019689
P-0043585
P-0044879
P-0042678
P-0043327
P-0043786
P-0044039
P-0044753

Here is another example provided by Niki:
https://bit.ly/2Kv3DM5

Revisit after heme germline fetch fix ... maybe curation issue?
Separate from dmp endpoint (coming from crdb?) for consent status? .. Check with Aijaz & Rebecca .. let Delicia know that an update may need to be made in CRDB for these samples.

**Comment by ao508** [comment]
Follow up with CVR team: In the endpoints we use for fetching a list of patients with Part C consent status "YES" there are patients reported that the CVR genomic variants endpoint reports as Part C consent status "NO".

**Comment by ao508** [comment]
Requeued the samples and they are now showing the correct Part C consent status, these samples will  be updated in the next successful import.
