### ISSUE TITLE
ARCHER/ACCESS cohorts use master list on lynx and consume samples on draco (Jira ticket CDCA-5)

### ISSUE THREAD

**Issue by ao508** [knowledgesystems/cmo-pipelines#700]
## OUTCOME
**What is the motivation for this card? Link issue or bug here.**
The CVR team has fixed and/or implemented master list endpoints for the ARCHER and ACCESS cohorts (Jira ticket [CDCA-5](http://virgo1.mskcc.org:8080/browse/CDCA-5)).

We've gotten the go ahead to start using the master list endpoints for these cohorts.

Per Rebecca w/MPath:

> Hi cBioPortal team,
> 
>We’ve deployed a new master list endpoint for ACCESS and an updated master list endpoint for Archer. They >are below:
 >
>http://lynx.mskcc.org:9770/get_signedout_samples/<session_id>/archer
> 
>http://lynx.mskcc.org:9770/get_signedout_samples/<session_id>/access
> 
>Please note they are at lynx:9770 instead of draco:9770. We’re currently transitioning these webservices from an old server (draco) to a newer server (lynx), so I deployed these new endpoints on our new server. Feel free to give them a try and let me know if there are any issues (currently ACCESS returns around 800 samples and Archer returns around 7,000 samples). Now that we have these master list endpoints, we’d recommend starting to mark Archer and ACCESS samples as consumed so there are fewer samples in your retrieve_variants calls.

**What is the "done" condition of this card?**
A clear and concise description of the done condition of a feature, process, or task that is being capture by this issue (it may be the completion of action items defined below).

The CVR pipeline uses the master list endpoint for the ARCHER and ACCESS cohorts.

ARCHER samples get consumed after import. (ACCESS samples are already being consumed).

This is also linked to Jira ticket [CDCA-7](http://virgo1.mskcc.org:8080/browse/CDCA-7) which should be verified/closed on completion of this card.

**Comment by n1zea144** [comment]
Per Rebecca w/MPath:

> Hi cBioPortal team,
> 
>We’ve deployed a new master list endpoint for ACCESS and an updated master list endpoint for Archer. They >are below:
 >
>http://lynx.mskcc.org:9770/get_signedout_samples/<session_id>/archer
> 
>http://lynx.mskcc.org:9770/get_signedout_samples/<session_id>/access
> 
>Please note they are at lynx:9770 instead of draco:9770. We’re currently transitioning these webservices from an old server (draco) to a newer server (lynx), so I deployed these new endpoints on our new server. Feel free to give them a try and let me know if there are any issues (currently ACCESS returns around 800 samples and Archer returns around 7,000 samples). Now that we have these master list endpoints, we’d recommend starting to mark Archer and ACCESS samples as consumed so there are fewer samples in your retrieve_variants calls.
