### ISSUE TITLE
Pipelines importer: refactor Google spreadsheet access

### ISSUE THREAD

**Issue by ao508** [knowledgesystems/cmo-pipelines#868]
Description:

Importers fail frequently due to errors access google worksheets (many times accessing case_ids_filters is the culprit).  This card captures the effort to minimize import failures by the following:

- add a timeout/retry when accessing google worksheets (15 sec?)
- remove references of unused worksheets (some research is needed for this, but most likely cancer studies, datatypes, and data sources is all that is needed).  See:
https://github.com/knowledgesystems/pipelines/blob/master/importer/src/main/java/org/mskcc/cbio/importer/config/internal/GDataImpl.java#L91
- See if there is an update to com.google.gdata.client.spreadsheet package.
- Create a new - history free version of the spreadsheet with only worksheets referenced  by code.

More information about case_ids_filter:

CaseIDsImpl.java corresponds to the "case_ids_filters" importer configuration spreadsheet. 

When GData attempts to establish a connection and read this spreadsheet it will sometimes throw an error that the resource could not be found. This behavior is inconsistent. Re-running the same admin tool command can result in a successful run.

**Comment by averyniceday** [comment]
Done Condition:
Successful import of msk_solid_heme with the new master & cleanup branch

If this doesn't work -- we need to replan and reestimate
